#!/usr/bin/env python3

import subprocess
import re

acpi = subprocess.check_output('acpi', shell=True).strip().decode('utf-8')
if acpi is '':
    exit(0)

is_charging = re.search('Discharging', acpi)
percentages = []
total = 0
for percentage in re.findall('(\d+)%', acpi):
    total += int(percentage)
    percentages.append(percentage)

if not is_charging:
    icon = '⚡'
else:
    if total > (200 * .75):
        icon = ''
    elif total > (200 * .5):
        icon = ''
    elif total > (200 * .25):
        icon = ''
    elif total > (200 * .05):
        icon = ''
    else:
        icon = ''

output = icon + '  '
output += '% / '.join(percentages) + '%'

print(output)
